//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormValidation.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class prodinfo
    {
        [DisplayName("Product ID")]
        public int prodid { get; set; }
        [DisplayName("ProductName")]
        [Required(ErrorMessage ="Product Name Required")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Product Name must be at least 4 characters long.")]
        public string prodname { get; set; }
        [DisplayName("Product Quantity")]
        [Required(ErrorMessage = "Product Quantity Required")]
        [Range(0,5,ErrorMessage ="Product Quantity must be within 0 to 5")]
        public Nullable<int> quantity { get; set; }
        [DisplayName("Product Description")]
        [Required(ErrorMessage = "Product Description Required")]
        [RegularExpression(@"[a-zA-z0-9]{3,}",ErrorMessage ="Description must be atleast 3 characters or more")]
        public string proddesc { get; set; }
    }
}
