//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqCRUD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class studentEntities1 : DbContext
    {
        public studentEntities1()
            : base("name=studentEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<studentreg> studentregs { get; set; }
    
        public virtual int delete_studreg(string rollno)
        {
            var rollnoParameter = rollno != null ?
                new ObjectParameter("rollno", rollno) :
                new ObjectParameter("rollno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_studreg", rollnoParameter);
        }
    
        public virtual ObjectResult<select_studreg_Result> select_studreg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_studreg_Result>("select_studreg");
        }
    
        public virtual int update_studreg(string rollno, string name, string phoneno)
        {
            var rollnoParameter = rollno != null ?
                new ObjectParameter("rollno", rollno) :
                new ObjectParameter("rollno", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var phonenoParameter = phoneno != null ?
                new ObjectParameter("phoneno", phoneno) :
                new ObjectParameter("phoneno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_studreg", rollnoParameter, nameParameter, phonenoParameter);
        }
    }
}
