//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorymvc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categorymvc()
        {
            this.productmvcs = new HashSet<productmvc>();
        }
    
        public int catid { get; set; }
        public string catname { get; set; }
        public string catdesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productmvc> productmvcs { get; set; }
    }
}
