//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMVC1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productmvc
    {
        public int catid { get; set; }
        public int prodid { get; set; }
        public string prodname { get; set; }
        public string proddesc { get; set; }
    
        public virtual categorymvc categorymvc { get; set; }
    }
}
